---
- name: PHP packages absent
  block:

    - name: "PHP {{ version }} packages absent"
      apt:
        pkg: "php{{ version }}*"
        state: absent
        purge: true
        autoclean: true
        autoremove: true

    - name: "PHP {{ version }} config files absent"
      file:
        path: "/etc/php/{{ version }}/"
        state: absent

  tags:
    - php
...
