---
- name: PHP packages absent
  block:

    - name: PHP packages absent
      apt:
        pkg: "php{{ version }}*"
        state: absent
      loop: "{{ php_versions_remove }}"
      loop_control:
        loop_var: version
        label: "php{{ version }}"

  tags:
    - php
...
