# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects PHP Ansible role.
#
# The Webarchitects PHP Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects PHP Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects PHP Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Sury PHP apt repo present
  block:

    - name: Python3 Debian present for deb822 module
      ansible.builtin.apt:
        pkg: python3-debian
        state: present

    - name: Package debsuryorg-archive-keyring.deb present
      ansible.builtin.apt:
        deb: https://packages.sury.org/debsuryorg-archive-keyring.deb
        state: present

    - name: Legacy PHP GPG key absent
      ansible.builtin.file:
        path: /etc/apt/keyrings/php.gpg
        state: absent

    # This key has been updated from /usr/share/keyrings/deb.sury.org-php.gpg
    - name: Stat the debsuryorg-archive-keyring.deb GPG key
      ansible.builtin.stat:
        path: /usr/share/keyrings/deb.sury.org-archive-keyring.gpg
      register: php_apt_key_path

    - name: The GPG key provided by the debsuryorg-archive-keyring.deb package is required
      ansible.builtin.assert:
        that:
          - php_apt_key_path.stat.exists | bool
        quiet: "{% if ansible_check_mode or ansible_verbosity >= 1 %}false{% else %}true{% endif %}"
        fail_msg: >-
          The GPG key provided by https://packages.sury.org/debsuryorg-archive-keyring.deb is required to configure the Sury PHP repo.

    - name: Configure the Sury apt repo when the GPG public key is present
      block:

        - name: Stat PHP repository sources file
          ansible.builtin.stat:
            path: /etc/apt/sources.list.d/php.sources
          register: php_sources_path

        - name: Read and backup PHP repository sources file
          block:

            - name: Read the PHP repository sources file
              ansible.builtin.include_tasks: sources_file.yml

            - name: Set a fact for the prior PHP repository sources file contents
              ansible.builtin.set_fact:
                php_sources_contents_prior: "{{ php_sources_contents }}"
              when: php_sources_contents is defined

            - name: Check PHP repository sources file present
              ansible.builtin.deb822_repository:
                allow_downgrade_to_insecure: false
                allow_insecure: false
                allow_weak: false
                architectures: "{{ ansible_facts.ansible_local.dpkg.arch }}"
                check_date: true
                check_valid_until: true
                components: main
                enabled: true
                name: php
                pdiffs: true
                signed_by: /usr/share/keyrings/deb.sury.org-archive-keyring.gpg
                suites: "{{ ansible_facts.distribution_release }}"
                types: deb
                uris: https://packages.sury.org/php/
              check_mode: true
              changed_when: false
              register: php_sources_check

            - name: Debug proposed php_sources_check.repo
              ansible.builtin.debug:
                var: php_sources_check.repo
                verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"

            - name: Backup old php.sources file
              ansible.builtin.command:
                cmd: >-
                  mv
                  /etc/apt/sources.list.d/php.sources
                  /etc/apt/sources.list.d/.php.sources.{{ php_date_timestamp }}.ansible.save
              args:
                creates: "/etc/apt/sources.list.d/.php.sources.{{ php_date_timestamp }}.ansible.save"
                removes: /etc/apt/sources.list.d/php.sources
              vars:
                php_date_timestamp: "{{ ansible_facts.date_time.iso8601_basic_short }}"
              when: php_sources_contents_prior != php_sources_check.repo | string | community.general.jc('ini')

          when: php_sources_path.stat.exists | bool

        - name: PHP repository sources file present
          ansible.builtin.deb822_repository:
            allow_downgrade_to_insecure: false
            allow_insecure: false
            allow_weak: false
            architectures: "{{ ansible_facts.ansible_local.dpkg.arch }}"
            check_date: true
            check_valid_until: true
            components: main
            enabled: true
            name: php
            pdiffs: true
            signed_by: /usr/share/keyrings/deb.sury.org-archive-keyring.gpg
            suites: "{{ ansible_facts.distribution_release }}"
            types: deb
            uris: https://packages.sury.org/php/
          register: php_sources

        - name: Print the changes in the PHP repository sources file  # noqa: no-handler
          block:

            - name: Debug updated php_sources.repo
              ansible.builtin.debug:
                var: php_sources.repo
                verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"

            - name: Diff PHP repository sources file update
              ansible.utils.fact_diff:
                before: "{{ php_sources_contents_prior | ansible.builtin.to_nice_yaml }}"
                after: "{{ php_sources.repo | string | community.general.jc('ini') | ansible.builtin.to_nice_yaml }}"
              when:
                - ( ansible_check_mode | bool ) or ( ansible_diff_mode | bool )
                - php_sources_contents_prior is defined
                - php_sources.repo is defined

          when: php_sources.changed | bool

        - name: PHP apt preferences present
          ansible.builtin.template:
            src: php.pref.j2
            dest: /etc/apt/preferences.d/php.pref
            mode: "0644"
            owner: root
            group: root
          environment:
            DEFAULT_MANAGED_STR: "{{ php_ansible_managed }}"
          register: php_preferences

        - name: Update apt cache and autoclean and autoremove
          block:

            - name: Update apt cache  # noqa: no-handler
              ansible.builtin.apt:
                update_cache: true
                cache_valid_time: 0
              check_mode: false
              changed_when: false

            - name: Apt autoclean and autoremove  # noqa: no-handler
              ansible.builtin.apt:
                upgrade: dist
                autoclean: true
                autoremove: true
                update_cache: false

          when: >-
            ( php_sources.changed | bool ) or
            ( php_preferences.changed | bool )
          tags:
            - molecule-idempotence-notest

      when: php_apt_key_path.stat.exists | bool

  when: php_sury | bool
  tags:
    - php
    - php_apt

- name: Sury PHP apt repo absent
  block:

    - name: Include file absent tasks
      ansible.builtin.include_tasks: file_absent.yml
      loop:
        - /etc/apt/keyrings/php.gpg
        - /etc/apt/sources.list.d/php.sources
        - /etc/apt/preferences.d/php.pref
      loop_control:
        loop_var: php_file_absent
        label: "{{ php_file_absent | ansible.builtin.basename }}"

    - name: Update apt cache  # noqa: no-handler
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      tags:
        - molecule-idempotence-notest

    - name: Apt autoclean and autoremove  # noqa: no-handler
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        update_cache: false
      tags:
        - molecule-idempotence-notest

  when: not php_sury | bool
  tags:
    - php
    - php_apt
...
