# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects PHP Ansible role.
#
# The Webarchitects PHP Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects PHP Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects PHP Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: PHP checks
  block:

    - name: Check the PHP versions installed
      ansible.builtin.command: /usr/sbin/phpquery -V
      check_mode: false
      changed_when: false
      register: php_phpquery_versions

    - name: Set a fact for the PHP versions installed
      ansible.builtin.set_fact:
        php_ver_installed: "{{ php_phpquery_versions.stdout_lines | sort }}"

    - name: Debug PHP versions that are installed
      ansible.builtin.debug:
        var: php_ver_installed
        verbosity: "{% if ansible_check_mode | bool %}1{% else %}2{% endif %}"

    - name: Include PHP FPM pool checks for each version of PHP present
      ansible.builtin.include_tasks: fpm_pool_check.yml
      loop: "{{ php_ver_installed }}"
      loop_control:
        loop_var: php_check_ver

    - name: Debug the PHP-FPM socket paths for all PHP versions
      ansible.builtin.debug:
        var: php_fpm_pools
        verbosity: 2
      when: php_fpm_pools is defined

    - name: Debug the pool names
      ansible.builtin.debug:
        msg: "{{ php_fpm_pools | community.general.json_query('[].pools[].name') }}"
        verbosity: 2
      when: php_fpm_pools is defined

    - name: Fail when there are duplicated PHP-FPM pool names
      ansible.builtin.fail:
        msg: >-
          PHP-FPM pool names need to be unique, these names are duplicated
          {{ php_fpm_pool_names | community.general.counter | ansible.builtin.dict2items | selectattr('value', '>', 1) |
          map(attribute='key') | join(', ') }}. You can use this role to remove the duplicates by running with
          --extra-vars "php_fpm_pool_check_fail=false".
      vars:
        php_fpm_pool_names: "{{ php_fpm_pools | community.general.json_query('[].pools[].name') | sort }}"
      when:
        - php_fpm_pools is defined
        - php_fpm_pool_check_fail | bool
        - php_fpm_pool_names | sort | length != php_fpm_pool_names | sort | unique | length

    - name: Warn when there are duplicated PHP-FPM pool names
      ansible.builtin.debug:
        msg: >-
          PHP-FPM pool names need to be unique, these names are duplicated
          {{ php_fpm_pool_names | community.general.counter | ansible.builtin.dict2items | selectattr('value', '>', 1) |
          map(attribute='key') | join(', ') }}. You can use this role to remove the duplicates by running with
          --extra-vars "php_fpm_pool_check_fail=false".
      vars:
        php_fpm_pool_names: "{{ php_fpm_pools | community.general.json_query('[].pools[].name') | sort }}"
      when:
        - php_fpm_pools is defined
        - not php_fpm_pool_check_fail | bool
        - php_fpm_pool_names | sort | length != php_fpm_pool_names | sort | unique | length

  tags:
    - php
    - php_cfg
    - php_conf
    - php_mods
...
