---
- name: PHP checks
  block:

    - name: Check that depreciated variables are not defined
      ansible.builtin.assert:
        that:
          - php_allow_url_include is not defined
          - php_apc_shm_size is not defined
          - phpcli_allow_local_infile is not defined
          - php_date_timezone is not defined
          - php_default_socket_timeout is not defined
          - php_disable_functions is not defined
          - php_dpkg is not defined
          - php_log is not defined
          - php_log_grep is not defined
          - php_max_execution_time is not defined
          - php_max_file_uploads is not defined
          - php_max_input_nesting_level is not defined
          - php_max_input_time is not defined
          - php_max_input_vars is not defined
          - php_memory_limit is not defined
          - php_mysqli_allow_local_infile is not defined
          - php_opcache_enable is not defined
          - php_opcache_interned_strings_buffer is not defined
          - php_opcache_max_accelerated_files is not defined
          - php_opcache_memory_consumption is not defined
          - php_opcache_revalidate_freq is not defined
          - php_opcache_use_cwd is not defined
          - php_opcache_validate_permission is not defined
          - php_opcache_validate_root is not defined
          - php_opcache_validate_timestamps is not defined
          - php_output_buffering is not defined
          - php_packages is not defined
          - php_phpquery is not defined
          - php_post_max_size is not defined
          - php_session_save_path is not defined
          - php_short_open_tag is not defined
          - php_upload_max_filesize is not defined
          - php_versioned_packages is not defined
          - php_www_pool_enabled is not defined
          - php_www_pool_ping_path is not defined
          - php_www_pool_pm is not defined
          - php_www_pool_pm_max_children is not defined
          - php_www_pool_pm_max_requests is not defined
          - php_www_pool_pm_max_spare_servers is not defined
          - php_www_pool_pm_min_spare_servers is not defined
          - php_www_pool_pm_process_idle_timeout is not defined
          - php_www_pool_pm_start_servers is not defined
          - php_www_pool_pm_status_path is not defined
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when:
        - php_check_legacy_variables is defined
        - php_check_legacy_variables | bool

    - name: Check that the distro is Debian Bullseye or Buster
      ansible.builtin.assert:
        that:
          - ansible_distribution_release is defined
          - ansible_distribution_release is regex("^buster|bullseye$")
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
        fail_msg: "The Linux distro {{ ansible_distribution }} {{ ansible_distribution_release }} is not supported by this role"

    - name: Check the PHP versions installed
      ansible.builtin.command: /usr/sbin/phpquery -V
      check_mode: false
      changed_when: false
      register: php_phpquery_versions

    - name: Set a fact for the PHP versions installed
      ansible.builtin.set_fact:
        php_ver_installed: "{{ php_phpquery_versions.stdout_lines }}"

    - name: Debug PHP versions installed
      ansible.builtin.debug:
        var: php_ver_installed
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

  tags:
    - php
...
