# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects PHP Ansible role.
#
# The Webarchitects PHP Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects PHP Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects PHP Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Check that the PHP version in the conf file path equals the PHP version being configured
  block:

    - name: Check that the PHP version in the conf file path equals the PHP version being configured
      ansible.builtin.assert:
        that:
          - php_conf_file is regex(php_conf_file_path_regex)
        fail_msg: "Path / version mismatch: {{ php_conf_file }} is set to be configured for PHP {{ php_ver }}"
      vars:
        php_conf_file_path_regex: "^[/]etc[/]php[/]{{ php_ver_chk }}[/].*"
      loop: "{{ php_conf_file_paths }}"
      loop_control:
        loop_var: php_conf_file

  tags:
    - php
    - php_cfg
    - php_conf
...
