---
- name: Update PHP config section
  block:

    - name: "Debug PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config section {{ cfg_sect.key }}"
      ansible.builtin.debug:
        var: cfg_sect
        verbosity: 2

    - name: "Include update variable tasks for PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config"
      ansible.builtin.include_tasks: config_variable.yml
      loop: "{{ cfg_sect.value | dict2items }}"
      loop_control:
        loop_var: cfg_var
        label: "{{ cfg_var.key }}"

  tags:
    - php
...
