---
- name: Update PHP config section
  block:

    - name: "Set a fact for the existing PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config section {{ cfg_sect.key }}"
      ansible.builtin.set_fact:
        php_section_existing: "{{ php_config_existing | community.general.json_query(php_jmespath_search) }}"
      vars:
        php_jmespath_search: '"{{ cfg_sect.key }}"'

    # - name: "Debug existing and proposed PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config section {{ cfg_sect.key }}"
    #   ansible.builtin.debug:
    #     msg:
    #       - "Existing value: {{ php_section_existing }}"
    #       - "Proposed value: {{ cfg_sect.value }}"
    #     verbosity: 2

    - name: "Include update variable tasks for PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config"
      ansible.builtin.include_tasks: config_variable.yml
      loop: "{{ cfg_sect.value | dict2items }}"
      loop_control:
        loop_var: cfg_var
        label: "{{ cfg_var.key }}"
      when: >
        ( php_section_existing | difference(cfg_sect.value) | length > 0 ) or
        ( cfg_sect.value | difference(php_section_existing) | length > 0 )

  tags:
    - php
...
