---
- name: Update PHP config variable
  block:

    # - name: "Set a fact for the existing PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config section {{ cfg_sect.key }} variable {{ cfg_var.key }}"
    #   ansible.builtin.set_fact:
    #     php_variable_existing: "{{ php_config_existing | community.general.json_query(php_jmespath_search) }}"
    #   vars:
    #     php_jmespath_search: '"{{ cfg_sect.key }}"."{{ cfg_var.key }}"'

    # - name: "Debug existing and proposed PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config section {{ cfg_sect.key }} variable {{ cfg_var.key }}"
    #   ansible.builtin.debug:
    #     msg:
    #       - "Existing value: {{ php_variable_existing }}"
    #       - "Proposed value: {{ cfg_var.value }}"
    #     verbosity: 2

    - name: "Update PHP {{ php_version.key }} SAPI {{ php_sapi.key }} config"
      community.general.ini_file:
        path: "/etc/php/{{ php_version.key }}/{{ php_sapi.key }}/php.ini"
        section: "{{ cfg_sect.key }}"
        option: "{{ cfg_var.key }}"
        value: "{{ cfg_var.value }}"
        state: present
        mode: 0644
      vars:
        php_jmespath_search: '"{{ cfg_sect.key }}"."{{ cfg_var.key }}"'
      when: php_config_existing | community.general.json_query(php_jmespath_search) != cfg_var.value

  tags:
    - php
...
