---
- name: Install and configure PHP
  block:

    - name: Include local facts tasks
      include_tasks: local_facts.yml

    - name: Include check tasks
      include_tasks: checks.yml

    - name: Include apt repo config for Sury PHP packages
      include_tasks: sury.yml

    - name: Debug fail
      fail:

    - name: PHP packages present
      apt:
        pkg: "{{ php_packages }}"
        state: present
        update_cache: true
      notify: Restart php-fpm

    - name: Which phpquery
      command: which phpquery
      check_mode: false
      changed_when: false
      register: php_phpquery_path
      failed_when: php_phpquery_path.rc != 0

    - name: Run phpquery to get the PHP version
      command: phpquery -V
      args:
        strip_empty_ends: true
      check_mode: false
      changed_when: false
      register: php_phpquery_version
      failed_when: >
        ( php_phpquery_version.stdout_lines | count > 1 ) or
        ( php_phpquery_version.stdout is not version('7.0', '>=') )

    - name: Set a variable for the PHP version
      set_fact:
        php_version: "{{ php_phpquery_version.stdout | trim }}"

    - name: Set an array for the PHP packages with version numbers in their names
      set_fact:
        php_version_packages: "{{ php_version_packages | default([]) }} + [ 'php{{ php_version }}-{{ php_package }}' ]"
      loop: "{{ php_versioned_packages }}"
      loop_control:
        loop_var: php_package
        label: "{{ php_package }}"

    - name: "PHP {{ php_version }} packages installed"
      apt:
        pkg: "{{ php_version_packages | default([]) }}"
        state: present
        update_cache: false
      notify: Restart php-fpm

    - name: APCu enabled
      command: phpenmod apcu
      when: ( "apcu" in php_versioned_packages )
      notify: Restart php-fpm

    - name: APCu disabled
      command: phpdismod apcu
      when: ( "apcu" not in php_versioned_packages )
      notify: Restart php-fpm

    - name: "PHP-FPM ini config /etc/php/{{ php_version }}/fpm/php.ini in place"
      template:
        src: "templates/php.ini.j2"
        dest: "/etc/php/{{ php_version }}/fpm/php.ini"
        mode: 0644
        backup: false
      notify: Restart php-fpm

    - name: "PHP CLI config /etc/php/{{ php_version }}/cli/php.ini in place"
      template:
        src: "templates/cli_php.ini.j2"
        dest: "/etc/php/{{ php_version }}/cli/php.ini"
        mode: 0644
        backup: false
      notify: Restart php-fpm

    - name: PHP-FPM www.conf pool disabled
      file:
        path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
        state: absent
      when: ( php_www_pool_enabled is defined ) and ( not php_www_pool_enabled )
      notify: Restart php-fpm

    - name: Check and enable the www pool
      block:

        - name: Include www pool server variable checks
          include_tasks: pool_check.yml
          when: php_www_pool_pm == "dynamic"
          vars:
            php_pm: "{{ php_www_pool_pm }}"
            php_pm_max_children: "{{ php_www_pool_pm_max_children }}"
            php_pm_start_servers: "{{ php_www_pool_pm_start_servers }}"
            php_pm_min_spare_servers: "{{ php_www_pool_pm_min_spare_servers }}"
            php_pm_max_spare_servers: "{{ php_www_pool_pm_max_spare_servers }}"

        - name: PHP-FPM www.conf pool enabled
          template:
            src: templates/www.conf.j2
            dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
            backup: false
          notify: Restart php-fpm

      when: ( php_www_pool_enabled is not defined ) or ( php_www_pool_enabled is defined and php_www_pool_enabled )

    - name: Check the PHP-FPM configuration
      command: "php-fpm{{ php_version }} --test"
      check_mode: false
      changed_when: false
      register: php_test
      failed_when: ( "test is successful" not in php_test.stderr )
      notify: Restart php-fpm

    - name: Check that /usr/bin/crontab exists
      stat:
        path: /usr/bin/crontab
      register: php_crontab

    # The log rotates once a week by default so this is a fairly crude metric but
    # it is good enough to flag up how often the max_children limits are being hit
    - name: Cron job to email root the results of grepping the logs for PHP-FPM pm.max_children
      cron:
        name: "Grep PHP{{ php_version }} log for pm.max_children"
        hour: "06"
        minute: "01"
        job: "grep 'server reached pm.max_children setting' /var/log/php{{ php_version }}-fpm.log | awk '{ print $5 }' | sed 's/]$//' | sort | uniq -c | sort -n"
        state: "{% if php_log_grep %}present{% else %}absent{% endif %}"
      when: php_crontab.stat.exists

  tags:
    - php
...
