---
- name: Get the Debian release codename
  shell: "lsb_release -c | awk '{ print $2 }'"
  register: phpfpm_debian_version_check
  check_mode: false
  changed_when: false
  tags:
    - phpfpm

- name: Set a fact for the Debian and PHP versions
  set_fact:
    phpfpm_debian_version: "{{ phpfpm_debian_version_check.stdout }}"
    phpfpm_version: "{% if phpfpm_debian_version_check.stdout == 'buster' %}7.3{% elif phpfpm_debian_version_check.stdout == 'bionic' %}7.2{% elif phpfpm_debian_version_check.stdout == 'stretch' %}7.0{% endif %}"
  tags:
    - phpfpm

- name: This role only has support for Debian Buster, Stretch and Ubuntu Bionic
  fail:
    msg: This role only has support for Debian Buster, Stretch and Ubuntu Bionic
  when: ( phpfpm_debian_version != "buster" ) and ( phpfpm_debian_version != "bionic" ) and ( phpfpm_debian_version != "stretch" )
  tags:
    - phpfpm

- name: PHP-FPM, php-date, php-pear and composer present
  apt:
    pkg: "{{ php_packages }}"
    state: present
  tags:
    - phpfpm

- name: PHP packages installed
  apt:
    pkg:
      - "php{{ phpfpm_version }}-{{ item }}"
    state: present
  loop: "{{ phpfpm_packages }}"
  tags:
    - phpfpm

- name: "/etc/php/{{ phpfpm_version }}/fpm/php.ini in place"
  template:
    src: "templates/php.ini.j2"
    dest: "/etc/php/{{ phpfpm_version }}/fpm/php.ini"
    backup: true
  tags:
    - phpfpm

- name: PHP-FPM www.conf pool disabled
  file:
    path: "/etc/php/{{ phpfpm_version }}/fpm/pool.d/www.conf"
    state: absent
  when: ( phpfpm_www_pool_enabled is defined ) and ( phpfpm_www_pool_enabled == False )
  tags:
    - phpfpm

- name: Include dynamic pool server variable checks
  include_tasks: dynamic_pool_check.yml
  when: phpfpm_www_pool_pm== "dynamic"
  vars:
    phpfpm_pm_max_children: "{{ phpfpm_www_pool_pm_max_children }}"
    phpfpm_pm_start_servers: "{{ phpfpm_www_pool_pm_start_servers }}"
    phpfpm_pm_min_spare_servers: "{{ phpfpm_www_pool_pm_min_spare_servers }}"
    phpfpm_pm_max_spare_servers: "{{ phpfpm_www_pool_pm_max_spare_servers }}"
  tags:
    - phpfpm

- name: PHP-FPM www.conf pool enabled
  template:
    src: templates/www.conf.j2
    dest: "/etc/php/{{ phpfpm_version }}/fpm/pool.d/www.conf"
    backup: true
  when: ( phpfpm_www_pool_enabled is not defined ) or ( phpfpm_www_pool_enabled == True )
  tags:
    - phpfpm
...
