---
- name: Get the Debian release codename
  shell: "lsb_release -c | awk '{ print $2 }'"
  register: phpfpm_debian_version_check
  changed_when: false

- name: Set a fact for the Debian version
  set_fact:
    phpfpm_debian_version: "{{ phpfpm_debian_version_check.stdout }}"

- name: Set the PHP version variable on stretch
  set_fact:
    phpfpm_version: "7.0"
  when: phpfpm_debian_version == "stretch"

- name: Set the PHP version variable on buster
  set_fact:
    phpfpm_version: "7.3"
  when: phpfpm_debian_version == "buster"

- name: This role only has support for Debian Stretch and Buster
  fail:
    msg: This role only has support for Debian Stretch and Buster
  when: ( phpfpm_debian_version != "stretch" ) and ( phpfpm_debian_version != "buster" )

- name: PHP-FPM and php-pear present
  apt:
    pkg:
      - "php{{ phpfpm_version }}-fpm"
      - php-pear
    state: present

- name: PHP packages installed
  apt:
    pkg:
      - "php{{ phpfpm_version }}-{{ item }}"
    state: present
  loop: "{{ phpfpm_packages }}"

- name: "/etc/php/{{ phpfpm_version }}/fpm/php.ini in place"
  template:
    src: "templates/{{ phpfpm_version }}.php.ini.j2"
    dest: "/etc/php/{{ phpfpm_version }}/fpm/php.ini"
    backup: true
