---
- name: Get the Debian release codename
  shell: "lsb_release -c | awk '{ print $2 }'"
  register: phpfpm_debian_version_check
  changed_when: false

- name: Set a fact for the Debian and PHP versions
  set_fact:
    phpfpm_debian_version: "{{ phpfpm_debian_version_check.stdout }}"
    phpfpm_version: "{% if apache_debian_version_check.stdout == 'buster' %}7.3{% elif users_debian_version == 'bionic' %}7.2{% elif apache_debian_version_check.stdout == 'stretch' %}7.0{% endif %}"

- name: This role only has support for Debian Buster, Stretch and Ubuntu Bionic
  fail:
    msg: This role only has support for Debian Buster, Stretch and Ubuntu Bionic
  when: ( phpfpm_debian_version != "buster" ) and ( phpfpm_debian_version != "bionic" ) and ( phpfpm_debian_version != "stretch" )

- name: PHP-FPM, php-pear and composer present
  apt:
    pkg:
      - composer
      - "php{{ phpfpm_version }}-fpm"
      - php-pear
    state: present

- name: PHP packages installed
  apt:
    pkg:
      - "php{{ phpfpm_version }}-{{ item }}"
    state: present
  loop: "{{ phpfpm_packages }}"

- name: "/etc/php/{{ phpfpm_version }}/fpm/php.ini in place"
  template:
    src: "templates/{{ phpfpm_version }}.php.ini.j2"
    dest: "/etc/php/{{ phpfpm_version }}/fpm/php.ini"
    backup: true
