---
- name: PHP SAPI module enabled / disabled tasks
  block:

    - name: "Debug the available modules for PHP version {{ version }}"
      debug:
        var: ansible_local.phpquery.versions[version].mods_available
        verbosity: 2
      when: ansible_local.phpquery.versions[version].mods_available is defined

    - name: "Debug the existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      debug:
        var: ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled
        verbosity: 2
      when: ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled is defined

    - name: "Debug the proposed modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      debug:
        var: sapi.value.modules_enabled
        verbosity: 2
      when: sapi.value.modules_enabled is defined

    - name: "Debug the absent modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      debug:
        var: sapi.value.modules_disabled
        verbosity: 2
      when: sapi.value.modules_disabled is defined

    - name: "Warn if a module is enabled but not set to be enabled for SAPI {{ sapi.key }} for PHP version {{ version }}"
      debug:
        msg: "Module {{ mod }} for for PHP version {{ version }} is not set to be enabled but it is enabled"
      loop: "{{ sapi.value.modules_enabled }}"
      loop_control:
        loop_var: mod
      when:
        - sapi.value.modules_enabled is defined
        - ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled is defined
        - mod not in ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled

    - name: "Warn as a module that doesn't exists is set to be absent"
      debug:
        msg: "Module {{ mod }} for PHP version {{ version }} doesn't exist so disabling it makes no sense"
      loop: "{{ sapi.value.modules_disabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"
      when:
        - sapi.value.modules_disabled is defined
        - ansible_local.phpquery.versions[version].mods_available is defined
        - mod not in ansible_local.phpquery.versions[version].mods_available

    - name: "Warn as module that doesn't exists is set to be enabled"
      debug:
        msg: "Module {{ mod }} for PHP version {{ version }} doesn't exist so enabling it makes no sense"
      loop: "{{ sapi.value.modules_enabled }}"
      loop_control:
        loop_var: mod
      when:
        - sapi.value.modules_enabled is defined
        - ansible_local.phpquery.versions[version].mods_available is defined
        - mod not in ansible_local.phpquery.versions[version].mods_available

    - name: "Include phpdismod tasks for absent modules that are existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      include_tasks: dismod.yml
      loop: "{{ sapi.value.modules_disabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"
      when:
        - sapi.value.modules_disabled is defined
        - ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled is defined
        - ansible_local.phpquery.versions[version].mods_available is defined
        - mod in sapi.value.modules_disabled
        - mod in ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled
        - mod in ansible_local.phpquery.versions[version].mods_available

    - name: "Include phpenmod tasks for proposed modules that are not existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      include_tasks: enmod.yml
      loop: "{{ sapi.value.modules_enabled }}"
      loop_control:
        loop_var: mod
      when:
        - sapi.value.modules_enabled is defined
        - ansible_local.phpquery.versions[version].mods_available is defined
        - ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled is defined
        - mod in sapi.value.modules_enabled
        - mod in ansible_local.phpquery.versions[version].mods_available
        - mod not in ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled

  tags:
    - php
...
