---
- name: PHP SAPI module enabled / disabled tasks
  block:

    - name: "Debug PHP version {{ version }}"
      debug:
        var: ansible_local.phpquery

    - name: "Debug PHP version {{ version }}"
      debug:
        var: ansible_local.phpquery[version]

    - name: "Debug the existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      debug:
        var: ansible_local.phpquery[version].sapis[sapi.key].modules

    - name: "Create an array for the existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      set_fact:
        php_modules_existing: "{{ ansible_local.phpquery[version].sapis[sapi.key].modules | sort }}"
      when:
        - ansible_local.phpquery[version].sapis[sapi.key].modules is defined
        - ansible_local.phpquery[version].sapis[sapi.key].modules != []

    - name: "Create an array for the proposed modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      set_fact:
        php_modules_proposed: "{{ sapi.value.modules_enabled | sort }}"
      when: ( sapi.value.modules_enabled is defined ) and ( sapi.value.modules_enabled != [] )

    - name: "Create an array for the absent modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      set_fact:
        php_modules_absent: "{{ sapi.value.modules_disabled | sort }}"
      when: ( sapi.value.modules_disabled is defined ) and ( sapi.value.modules_disabled != [] )

    - name: "Include phpdismod tasks for absent modules that are existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      include_tasks: phpdismod.yml
      loop: "{{ php_modules_absent }}"
      loop_control:
        loop_var: mod
      when:
        - ( php_modules_absent is defined ) and ( php_modules_absent != [] )
        - ( mod in php_modules_existing )

    - name: "Include phpenmod tasks for proposed modules that are not existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      include_tasks: phpenmod.yml
      loop: "{{ php_modules_proposed | difference(php_modules_existing) }}"
      loop_control:
        loop_var: mod
      when:
        - ( php_modules_proposed | difference(php_modules_existing) ) != []
        - ( mod in php_modules_proposed )
        - ( mod not in php_modules_existing )

  tags:
    - php
...
