---
- name: PHP SAPI module enabled / disabled tasks
  block:

    - name: Available modules
      block:

        - name: "Debug the available modules for PHP version {{ version }}"
          debug:
            var: ansible_local.phpquery.versions[version].mods_available
            verbosity: 2

        - name: "Create an array for the existing modules for PHP version {{ version }}"
          set_fact:
            php_modules_available: "{{ ansible_local.phpquery.versions[version].mods_available | sort }}"

      when:
        - ansible_local.phpquery.versions[version].mods_available is defined
        - ansible_local.phpquery.versions[version].mods_available != []

    - name: Existing modules
      block:

        - name: "Debug the existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
          debug:
            var: ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled
            verbosity: 2

        - name: "Create an array for the existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
          set_fact:
            php_modules_available: "{{ ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled | sort }}"

      when:
        - ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled is defined
        - ansible_local.phpquery.versions[version].sapis[sapi.key].mods_enabled != []

    - name: Proposed modules
      block:

        - name: "Debug the proposed modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
          debug:
            var: sapi.value.modules_enabled
            verbosity: 2

        - name: "Create an array for the proposed modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
          set_fact:
            php_modules_proposed: "{{ sapi.value.modules_enabled | sort }}"

      when: ( sapi.value.modules_enabled is defined ) and ( sapi.value.modules_enabled != [] )

    - name: Absent modules
      block:

        - name: "Debug the absent modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
          debug:
            var: sapi.value.modules_disabled

        - name: "Create an array for the absent modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
          set_fact:
            php_modules_absent: "{{ sapi.value.modules_disabled | sort }}"

        - name: "Fail as a module that doesn't exists is set to be absent"
          fail:
            msg: "Module {{ mod }} for PHP version {{ version }} doesn't exist so disabling it makes no sense"
          loop: "{{ php_modules_absent }}"
          loop_control:
            loop_var: mod
            label: "{{ mod }}"
          when:
            - ( php_modules_absent is defined ) and ( php_modules_absent != [] )
            - ( php_modules_existing is defined ) and ( php_modules_existing != [] )
            - ( mod not in php_modules_available )

        - name: "Include phpdismod tasks for absent modules that are existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
          include_tasks: dismod.yml
          loop: "{{ php_modules_absent }}"
          loop_control:
            loop_var: mod
            label: "{{ mod }}"
          when:
            - ( php_modules_absent is defined ) and ( php_modules_absent != [] )
            - ( php_modules_existing is defined ) and ( php_modules_existing != [] )
            - ( mod in php_modules_existing )

      when: ( sapi.value.modules_disabled is defined ) and ( sapi.value.modules_disabled != [] )

    - name: "Fail as module that doesn't exists is set to be enabled"
      fail:
        msg: 
      loop: "{{ php_modules_proposed | difference(php_modules_existing) }}"
      loop_control:
        loop_var: mod
      when:
        - ( php_modules_proposed is defined ) and ( php_modules_proposed != [] )
        - ( php_modules_existing is defined ) and ( php_modules_existing != [] )
        - ( php_modules_proposed | difference(php_modules_existing) ) != []
        - ( mod in php_modules_proposed )
        - ( mod not in php_modules_available )

    - name: "Include phpenmod tasks for proposed modules that are not existing modules for SAPI {{ sapi.key }} for PHP version {{ version }}"
      include_tasks: enmod.yml
      loop: "{{ php_modules_proposed | difference(php_modules_existing) }}"
      loop_control:
        loop_var: mod
      when:
        - ( php_modules_proposed is defined ) and ( php_modules_proposed != [] )
        - ( php_modules_existing is defined ) and ( php_modules_existing != [] )
        - ( php_modules_proposed | difference(php_modules_existing) ) != []
        - ( mod in php_modules_proposed )
        - ( mod not in php_modules_existing )

  tags:
    - php
...
