---
- name: PHP present
  block:

    - name: Debug the difference between php.packages and ansible_local.php.packages
      ansible.builtin.debug:
        msg:
          - "{{ php.packages | difference(ansible_local.php.packages) }}"
        verbosity: 2
      when:
        - ansible_local.php.packages is defined
        - ansible_local.php.packages | length > 0

    - name: PHP packages present
      ansible.builtin.apt:
        pkg: "{{ php.packages }}"
        state: present
      register: php_packages_present
      when: >
        ( ( ansible_local.php.state == "absent" ) or
        ( ( ansible_local.php.packages is defined ) and
        ( php.packages | difference(ansible_local.php.packages) | length > 0 ) ) )

    - name: Re-read Ansible local facts
      ansible.builtin.setup:
        filter: ansible_local
      when: ( php_packages_absent is defined and php_packages_absent.changed | bool )

    - name: PHP packages absent
      block:

        - name: Debug the difference between ansible_local.php.packages and php.packages
          ansible.builtin.debug:
            msg:
              - "{{ ansible_local.php.packages | difference(php.packages) }}"
            verbosity: 2

        - name: PHP packages absent
          ansible.builtin.apt:
            pkg: "{{ ansible_local.php.packages | difference(php.packages) }}"
            state: absent
            purge: true
          register: php_packages_absent

      when:
        - ansible_local.php.state == "present"
        - ansible_local.php.packages is defined
        - ansible_local.php.packages | length > 0
        - ansible_local.php.packages | difference(php.packages) | length > 0

    - name: Re-read Ansible local facts
      ansible.builtin.setup:
        filter: ansible_local
      when: ( php_packages_absent is defined and php_packages_absent.changed | bool )

  tags:
    - php
...
