---
- name: PHP absent
  block:

    - name: PHP absent
      ansible.builtin.apt:
        pkg: php*
        state: absent
        purge: true
      register: php_absent

    - name: Re-read Ansible local facts
      ansible.builtin.setup:
        filter: ansible_local
      when: php_absent is defined and php_absent.changed

  tags:
    - php
...
