---
- name: Disable PHP module
  block:

    - name: "Disable module {{ mod }} for SAPI {{ sapi.key }} for PHP version {{ version }}"
      command: phpdismod -v "{{ version }}" -s "{{ sapi.key }}" "{{ mod }}"
      register: php_mod_disabled

  tags:
    - php
...
