---
- name: PHP packages configured
  block:

    - name: PHP versions absent
      ansible.builtin.apt:
        pkg: "php{{ php_ver }}*"
        state: absent
        update_cache: true
        cache_valid_time: 60
        autoclean: true
        autoremove: true
        purge: true
      loop: "{{ php_ver_absent }}"
      loop_control:
        loop_var: php_ver
      register: php_versions_absent
      when:
        - php_pkg_absent is defined
        - php_pkg_absent != []

    - name: PHP packages absent
      ansible.builtin.apt:
        pkg: "{{ php_pkg_absent }}"
        state: absent
        update_cache: true
        cache_valid_time: 60
        autoclean: true
        autoremove: true
        purge: true
      register: php_packages_absent
      when:
        - php_pkg_absent is defined
        - php_pkg_absent != []

    - name: PHP packages present
      ansible.builtin.apt:
        pkg: "{{ php_pkg_present }}"
        state: latest
        autoclean: true
        autoremove: true
        update_cache: true
        cache_valid_time: 60
      register: php_packages_present
      when:
        - php_pkg_present is defined
        - php_pkg_present != []

    - name: Apt dist upgrade
      ansible.builtin.apt:
        upgrade: dist
        autoclean: true
        autoremove: true
        update_cache: true
        cache_valid_time: 60
      when: >-
        ( ( php_versions_absent is defined ) and ( php_versions_absent.changed | bool ) ) or
        ( ( php_packages_absent is defined ) and ( php_packages_absent.changed | bool ) ) or
        ( ( php_packages_present is defined ) and ( php_packages_present.changed | bool ) )

  tags:
    - php
    - php_pkg
...
