---
# https://www.php.net/manual/en/install.fpm.configuration.php
- name: Check that the PHP-FPM pool pm servers and children limits are sane
  block:

    - name: Print variables for debugging
      debug:
        msg:
          - "php_pm is a {{ php_pm | type_debug }} with the value: {{ php_pm }}"
          - "php_pm_start_servers is a {{ php_pm_start_servers | type_debug }} with the value: {{ php_pm_start_servers }}"
          - "php_pm_max_children is a {{ php_pm_max_children | type_debug }} with the value {{ php_pm_max_children }}"
          - "php_pm_min_spare_servers is a {{ php_pm_min_spare_servers | type_debug }} with the value {{ php_pm_min_spare_servers }}"
          - "php_pm_max_spare_servers is a {{ php_pm_max_spare_servers | type_debug }} with the value: {{ php_pm_max_spare_servers }}"
        verbosity: 2

    - name: Ensure that pm is set to static, ondemand or dynamic
      assert:
        that:
          - php_pm is regex("^static|ondemand|dynamic$")
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Ensure that pm.max_children is defined, numeric and is greater than 1
      assert:
        that:
          - php_pm_max_children is defined
          - ( php_pm_max_children | string ) is regex("^[0-9]+$")
          - ( php_pm_max_children | int ) >= 1
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Conditional pm dynamic pool checks
      block:

        - name: Ensure that pm.start_servers, pm.min_spare_servers and pm.max_spare_servers are defined and numeric
          assert:
            that:
              - php_pm_start_servers is defined
              - ( php_pm_start_servers | string ) is regex("^[0-9]+$")
              - php_pm_min_spare_servers is defined
              - ( php_pm_min_spare_servers | string ) is regex("^[0-9]+$")
              - php_pm_max_spare_servers is defined
              - ( php_pm_max_spare_servers | string ) is regex("^[0-9]+$")
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

        - name: Ensure that pm.max_children, pm.start_servers, pm.min_spare_servers and pm.max_spare_servers are greater than or equal to 1
          assert:
            that:
              - php_pm_max_children | int >= 1
              - php_pm_start_servers | int >= 1
              - php_pm_min_spare_servers | int >= 1
              - php_pm_max_spare_servers | int >= 1
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

        - name: Ensure that pm.max_children is greater than or equal to pm.start_servers, pm.min_spare_servers and pm.max_spare_servers
          assert:
            that:
              - php_pm_max_children | int >= php_pm_start_servers | int
              - php_pm_max_children | int >= php_pm_min_spare_servers | int
              - php_pm_max_children | int >= php_pm_max_spare_servers | int
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

        - name: Ensure that pm.start_servers is be greater than pm.min_spare_servers and less than or equal to pm.max_spare_servers
          assert:
            that:
              - php_pm_start_servers | int >= php_pm_min_spare_servers | int
              - php_pm_start_servers | int <= php_pm_max_spare_servers | int
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

        - name: Ensure that pm.max_spare_servers is greater than pm.min_spare_servers
          assert:
            that:
              - php_pm_max_spare_servers | int >= php_pm_min_spare_servers | int
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

      when: php_pm == "dynamic"

  tags:
    - php
...
