---
- name: PHP packages present
  block:

    - name: "PHP {{ version }} packages present"
      apt:
        pkg: "{{ php_version_packages | default([]) }} + [ 'php{{ version }}-{{ php_package }}' ]"
        state: present
      loop: "{{ php_versioned_packages }}"
      loop_control:
        loop_var: php_package
        label: "{{ php_package }}"
      notify: Restart php-fpm

  tags:
    - php
...
