---
- name: PHP SAPI module checks
  block:

    - name: "Check that no SAPI modules for {{ sapi.key }} are set to be enabled and disabled at the same time for PHP {{ version }}"
      assert:
        that:
          - mod not in sapi.modules_disabled
      loop: "{{ sapi.modules_enabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"

  tags:
    - php
...
