---
- name: PHP SAPI module checks
  block:

    - name: "Check that no SAPI modules for {{ sapi.key }} are set to be enabled and disabled at the same time for PHP {{ version }}"
      ansible.builtin.assert:
        that:
          - mod not in sapi.value.modules_disabled
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
        fail_msg: "The PHP module {{ mod }} appears to in both the modules_enabled and modules_disabled arrays for SAPI {{ sapi.key }} for PHP version {{ version }}"
      loop: "{{ sapi.value.modules_enabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"

  tags:
    - php
...
