---
- name: PHP SAPI checks
  block:

    - name: "Check that SAPI is not set to be present when PHP {{ version }} is set to be removed"
      assert:
        that:
          - sapi.value.state == "absent"
        fail_msg: "SAPI {{ sapi.key }} is not set to be absent for PHP {{ version }}, yet PHP {{ version }} is set to be removed."
      loop: "{{ php_versions[version].sapis | dict2items }}"
      loop_control:
        loop_var: sapi
        label: "{{ sapi.key }}"

    - name: "Check that no SAPI modules are set to be enabled and disabled at the same time for PHP {{ version }}"
      include_tasks: sapi_module_checks.yml
      loop: "{{ php_versions[version].sapis | dict2items }}"
      loop_control:
        loop_var: sapi
        label: "{{ sapi.key }}"
      when:
        - ( sapi.value.state is defined ) and ( sapi.value.state == "present" )
        - ( sapi.value.modules_enabled is defined ) and ( sapi.value.modules_enabled != [] )
        - ( sapi.value.modules_disabled is defined ) and ( sapi.value.modules_disabled != [] )

  tags:
    - php
...
