---
- name: PHP SAPI configuration files absent
  block:

    - name: "SAPI configuration absent for PHP {{ version }}"
      ansible.builtin.file:
        path: "/etc/php/{{ version }}/{{ sapi.key }}"
        state: absent
      loop: "{{ php_versions[version].sapis | dict2items }}"
      loop_control:
        loop_var: sapi
        label: "{{ sapi.key }}"
      when: ( sapi.value.state is defined ) and ( sapi.value.state == "absent" )

  tags:
    - php
...
