---
- name: Check that no SAPI modules are set to be enabled and disabled at the same time
  block:

    - name: "Loop through the modules_enabled for SAPI {{ sapi.key }} for PHP {{ version }} to check that none are also set to be disabled"
      assert:
        that:
          - mod not in sapi.value.modules_disabled
      loop: "{{ sapi.value.modules_enabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"
      when:
        - ( sapi.value.modules_enabled is defined ) and ( sapi.value.modules_enabled != [] )
        - ( sapi.value.modules_disabled is defined ) and ( sapi.value.modules_disabled != [] )

  tags:
    - php
...
