---
- name: PHP SAPI checks
  block:

    - name: "Include SAPI module checks for PHP {{ version }}"
      ansible.builtin.include_tasks: sapi_module_checks.yml
      loop: "{{ php_versions[version].sapis | dict2items }}"
      loop_control:
        loop_var: sapi
        label: "{{ sapi.key }}"
      when:
        - ( sapi.value.state is defined ) and ( sapi.value.state == "present" )
        - ( sapi.value.modules_enabled is defined ) and ( sapi.value.modules_enabled != [] )
        - ( sapi.value.modules_disabled is defined ) and ( sapi.value.modules_disabled != [] )

  tags:
    - php
...
