---
- name: Check SAPI state
  block:

    - name: "Debug PHP {{ version }} SAPI {{ sapi.key }} state"
      debug:
        var: sapi.value.state
        verbosity: 2

    - name: "Check that SAPI {{ sapi.key }} is not set to be present when PHP {{ version }} is set to be removed"
      assert:
        that:
          - sapi.value.state == "absent"
        fail_msg: "SAPI {{ sapi.key }} is not set to be absent for PHP {{ version }}, yet PHP {{ version }} is set to be removed."
    #   loop:
    #     - apache2
    #     - cli
    #     - fpm
    #     - phpdbg
    #   loop_control:
    #     loop_var: sapi
    #     label: "{{ sapi.key }}"
    #   when:
    #     - php_versions[version].sapis is defined
    #     - php_versions[version].sapis.sapi is defined
    #     - php_versions[version].sapis.sapi.state is defined

  tags:
    - php
...
