---
- name: PHP SAPI checks
  block:

    - name: Debug version
      debug:
        var: version

    - name: Debug
      debug:
        var: ansible_local.phpquery.versions['7.4'].sapis

    - name: "Set a variable for the existing SAPI array for PHP {{ version }}" 
      set_fact:
        sapis: "{{ ansible_local.phpquery.versions[~ version].sapis }}"

    - name: Generate an array of existing PHP SAPIs 
      set_fact:
        php_existing_sapis: "{{ php_existing_sapis | default([]) }} + [ '{{ existing_sapi.key }}' ]"
      when:
        - ansible_local.phpquery.versions[version] is defined
        - existing_sapi.value.state == "present"
      loop: "{{ sapis | dict2items }}"
      loop_control:
        loop_var: existing_sapi
        label: "{{ existing_sapi.key }}"

    - name: Debug existing PHP SAPIs
      debug:
        ver: php_existing_sapis
      when: php_existing_sapis is defined

  tags:
    - php
...
