# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects PHP Ansible role.
#
# The Webarchitects PHP Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects PHP Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects PHP Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Read the PHP repository sources file
  block:

    - name: Slurp /etc/apt/sources.list.d/php.sources
      ansible.builtin.slurp:
        src: /etc/apt/sources.list.d/php.sources
      register: php_sources_contents_b64encoded

    - name: Decode the base64 encoded version of /etc/apt/sources.list.d/php.sources
      ansible.builtin.set_fact:
        php_sources_contents: "{{ php_sources_contents_b64encoded['content'] | ansible.builtin.b64decode | community.general.jc('ini') }}"

    - name: Print the contents of /etc/apt/sources.list.d/php.sources
      ansible.builtin.debug:
        var: php_sources_contents
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"
      tags:
        - debug

  when: php_sources_path.stat.exists | bool
  tags:
    - php
    - php_apt
...
